spring:
  application:
    name: PicLocket

  datasource:
    url: jdbc:mysql://localhost:3306/piclocket
    username: piclocket_user
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
