spring:
  application:
    name: PicLocket

  datasource:
    url: jdbc:mysql://localhost:3306/piclocket
    username: piclocket_user
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
